# Generated by Django 4.2 on 2023-04-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_remove_chatmessage_date_sent_chatmessage_sent_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.CharField(max_length=1800),
        ),
    ]
