# Generated by Django 4.2 on 2023-05-05 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_chatmessage_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="from_chat_group",
            new_name="chat_group",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="sent_on",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="from_user",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="chatgroup",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="chatgroupmembership",
            name="data_joined",
        ),
        migrations.AddField(
            model_name="chatgroup",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="chatgroupmembership",
            name="joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
