name: chatter CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  python_lint_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[rest]

      - name: Lint with flake8
        run: flake8 . --count --show-source --statistics

      - name: Verify formatting with black
        run: black . --check --diff

      - name: Verify sort formatting with isort
        run: isort **/*.py --check -v

      - name: Create .env file
        run: |
          echo SECRET_KEY="${{ secrets.SECRET_TEST_KEY }}" >> .env

      - name: Run tests
        run: |
          pytest
